// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  botId: __t.u64().primaryKey().name("bot_id"),
  rating: __t.i32(),
  matchesPlayed: __t.u32().name("matches_played"),
  wins: __t.u32(),
  totalScore: __t.i64().name("total_score"),
  lastPlayed: __t.option(__t.timestamp()).name("last_played"),
  openskillMu: __t.f64().name("openskill_mu"),
  openskillSigma: __t.f64().name("openskill_sigma"),
});
