// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  humanIdentity: __t.identity(),
  addedAt: __t.timestamp(),
  addedBy: __t.option(__t.identity()),
});
export type Admin = __Infer<typeof Admin>;

export const Auction = __t.object("Auction", {
  id: __t.u64(),
  matchId: __t.u64(),
  letter: __t.string(),
  opensAt: __t.timestamp(),
  closesAt: __t.timestamp(),
  get status() {
    return AuctionStatus;
  },
});
export type Auction = __Infer<typeof Auction>;

export const AuctionResult = __t.object("AuctionResult", {
  auctionId: __t.u64(),
  matchId: __t.u64(),
  letter: __t.string(),
  winnerBotId: __t.option(__t.u64()),
  paid: __t.i64(),
  closedAt: __t.timestamp(),
});
export type AuctionResult = __Infer<typeof AuctionResult>;

export const AuctionSchedule = __t.object("AuctionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type AuctionSchedule = __Infer<typeof AuctionSchedule>;

// The tagged union or sum type for the algebraic type `AuctionStatus`.
export const AuctionStatus = __t.enum("AuctionStatus", {
  Open: __t.unit(),
  Closed: __t.unit(),
});
export type AuctionStatus = __Infer<typeof AuctionStatus>;

export const AuctionTopBid = __t.object("AuctionTopBid", {
  auctionId: __t.u64(),
  matchId: __t.u64(),
  topBid: __t.i64(),
  visible: __t.bool(),
});
export type AuctionTopBid = __Infer<typeof AuctionTopBid>;

export const AuctionTopBidArchive = __t.object("AuctionTopBidArchive", {
  auctionId: __t.u64(),
  matchId: __t.u64(),
  topBid: __t.i64(),
});
export type AuctionTopBidArchive = __Infer<typeof AuctionTopBidArchive>;

// The tagged union or sum type for the algebraic type `AuctionType`.
export const AuctionType = __t.enum("AuctionType", {
  FirstPrice: __t.unit(),
  Vickrey: __t.unit(),
});
export type AuctionType = __Infer<typeof AuctionType>;

export const BagLetter = __t.object("BagLetter", {
  id: __t.u64(),
  matchId: __t.u64(),
  letter: __t.string(),
  remaining: __t.u32(),
});
export type BagLetter = __Infer<typeof BagLetter>;

export const Bot = __t.object("Bot", {
  id: __t.u64(),
  name: __t.string(),
  teamId: __t.u64(),
  isSimulated: __t.bool(),
  get strategy() {
    return BotStrategy;
  },
  createdAt: __t.timestamp(),
});
export type Bot = __Infer<typeof Bot>;

export const BotCredential = __t.object("BotCredential", {
  identity: __t.identity(),
  botId: __t.u64(),
  connected: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type BotCredential = __Infer<typeof BotCredential>;

export const BotStats = __t.object("BotStats", {
  botId: __t.u64(),
  rating: __t.i32(),
  matchesPlayed: __t.u32(),
  wins: __t.u32(),
  totalScore: __t.i64(),
  lastPlayed: __t.option(__t.timestamp()),
});
export type BotStats = __Infer<typeof BotStats>;

// The tagged union or sum type for the algebraic type `BotStrategy`.
export const BotStrategy = __t.enum("BotStrategy", {
  Human: __t.unit(),
  Cheapskate: __t.unit(),
  ValueBidder: __t.unit(),
  Aggressive: __t.unit(),
});
export type BotStrategy = __Infer<typeof BotStrategy>;

export const CredentialNonce = __t.object("CredentialNonce", {
  id: __t.u64(),
  code: __t.string(),
  botId: __t.u64(),
  creator: __t.identity(),
  expiresAt: __t.timestamp(),
});
export type CredentialNonce = __Infer<typeof CredentialNonce>;

export const Holding = __t.object("Holding", {
  id: __t.u64(),
  matchId: __t.u64(),
  botId: __t.u64(),
  letter: __t.string(),
  count: __t.u32(),
});
export type Holding = __Infer<typeof Holding>;

export const HumanLink = __t.object("HumanLink", {
  webIdentity: __t.identity(),
  humanIdentity: __t.identity(),
  linkedAt: __t.timestamp(),
});
export type HumanLink = __Infer<typeof HumanLink>;

export const Lobby = __t.object("Lobby", {
  id: __t.u64(),
  get status() {
    return LobbyStatus;
  },
  opensAt: __t.timestamp(),
  closesAt: __t.timestamp(),
  maxSize: __t.u32(),
  get auctionType() {
    return AuctionType;
  },
  resolvedMatchId: __t.option(__t.u64()),
});
export type Lobby = __Infer<typeof Lobby>;

export const LobbyMember = __t.object("LobbyMember", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  botId: __t.u64(),
  joinedAt: __t.timestamp(),
});
export type LobbyMember = __Infer<typeof LobbyMember>;

// The tagged union or sum type for the algebraic type `LobbyStatus`.
export const LobbyStatus = __t.enum("LobbyStatus", {
  Open: __t.unit(),
  Resolved: __t.unit(),
  Cancelled: __t.unit(),
});
export type LobbyStatus = __Infer<typeof LobbyStatus>;

export const LobbyTimeoutSchedule = __t.object("LobbyTimeoutSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
});
export type LobbyTimeoutSchedule = __Infer<typeof LobbyTimeoutSchedule>;

export const Match = __t.object("Match", {
  id: __t.u64(),
  get status() {
    return MatchStatus;
  },
  currentRound: __t.u32(),
  currentAuctionId: __t.option(__t.u64()),
  bagTotal: __t.u32(),
  get auctionType() {
    return AuctionType;
  },
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
  endedAt: __t.option(__t.timestamp()),
});
export type Match = __Infer<typeof Match>;

export const MatchParticipant = __t.object("MatchParticipant", {
  id: __t.u64(),
  matchId: __t.u64(),
  botId: __t.u64(),
  balance: __t.i64(),
  score: __t.i64(),
});
export type MatchParticipant = __Infer<typeof MatchParticipant>;

// The tagged union or sum type for the algebraic type `MatchStatus`.
export const MatchStatus = __t.enum("MatchStatus", {
  Lobby: __t.unit(),
  Running: __t.unit(),
  Ended: __t.unit(),
});
export type MatchStatus = __Infer<typeof MatchStatus>;

export const MyTeam = __t.object("MyTeam", {
  teamId: __t.u64(),
  teamName: __t.string(),
  botId: __t.u64(),
  botName: __t.string(),
  get role() {
    return TeamRole;
  },
  credentialCount: __t.u32(),
});
export type MyTeam = __Infer<typeof MyTeam>;

export const PendingBid = __t.object("PendingBid", {
  id: __t.u64(),
  auctionId: __t.u64(),
  bidderBotId: __t.u64(),
  amount: __t.i64(),
  submittedAt: __t.timestamp(),
});
export type PendingBid = __Infer<typeof PendingBid>;

export const Team = __t.object("Team", {
  id: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Team = __Infer<typeof Team>;

export const TeamMember = __t.object("TeamMember", {
  id: __t.u64(),
  teamId: __t.u64(),
  user: __t.identity(),
  get role() {
    return TeamRole;
  },
  joinedAt: __t.timestamp(),
});
export type TeamMember = __Infer<typeof TeamMember>;

// The tagged union or sum type for the algebraic type `TeamRole`.
export const TeamRole = __t.enum("TeamRole", {
  Owner: __t.unit(),
  Member: __t.unit(),
});
export type TeamRole = __Infer<typeof TeamRole>;

export const Tournament = __t.object("Tournament", {
  id: __t.u64(),
  get status() {
    return TournamentStatus;
  },
  swissRoundsTotal: __t.u32(),
  currentRound: __t.u32(),
  topCut: __t.u32(),
  matchSize: __t.u32(),
  get auctionType() {
    return AuctionType;
  },
  createdAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
});
export type Tournament = __Infer<typeof Tournament>;

export const TournamentEntry = __t.object("TournamentEntry", {
  id: __t.u64(),
  tournamentId: __t.u64(),
  botId: __t.u64(),
  swissPoints: __t.i32(),
  eliminated: __t.bool(),
});
export type TournamentEntry = __Infer<typeof TournamentEntry>;

export const TournamentMatch = __t.object("TournamentMatch", {
  id: __t.u64(),
  tournamentId: __t.u64(),
  matchId: __t.u64(),
  round: __t.u32(),
  get phase() {
    return TournamentPhase;
  },
});
export type TournamentMatch = __Infer<typeof TournamentMatch>;

// The tagged union or sum type for the algebraic type `TournamentPhase`.
export const TournamentPhase = __t.enum("TournamentPhase", {
  Swiss: __t.unit(),
  Bracket: __t.unit(),
  Final: __t.unit(),
});
export type TournamentPhase = __Infer<typeof TournamentPhase>;

// The tagged union or sum type for the algebraic type `TournamentStatus`.
export const TournamentStatus = __t.enum("TournamentStatus", {
  Lobby: __t.unit(),
  Swiss: __t.unit(),
  Bracket: __t.unit(),
  Final: __t.unit(),
  Ended: __t.unit(),
});
export type TournamentStatus = __Infer<typeof TournamentStatus>;

export const WordPlay = __t.object("WordPlay", {
  id: __t.u64(),
  matchId: __t.u64(),
  botId: __t.u64(),
  word: __t.string(),
  baseScore: __t.i64(),
  bonus: __t.i64(),
  totalReward: __t.i64(),
  playedAt: __t.timestamp(),
});
export type WordPlay = __Infer<typeof WordPlay>;

