// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAdminReducer from "../add_admin_reducer";
import BackfillEloReducer from "../backfill_elo_reducer";
import BackfillTopBidArchiveReducer from "../backfill_top_bid_archive_reducer";
import BootstrapAdminReducer from "../bootstrap_admin_reducer";
import ClaimCredentialReducer from "../claim_credential_reducer";
import ConnectIdReducer from "../connect_id_reducer";
import CreateTeamReducer from "../create_team_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import JoinTeamReducer from "../join_team_reducer";
import LeaveTeamReducer from "../leave_team_reducer";
import MintCredentialNonceReducer from "../mint_credential_nonce_reducer";
import PromoteToOwnerReducer from "../promote_to_owner_reducer";
import RemoveAdminReducer from "../remove_admin_reducer";
import SpawnSimulatedBotReducer from "../spawn_simulated_bot_reducer";
import StartTournamentReducer from "../start_tournament_reducer";
import SubmitBidReducer from "../submit_bid_reducer";
import SubmitWordReducer from "../submit_word_reducer";

export type AddAdminParams = __Infer<typeof AddAdminReducer>;
export type BackfillEloParams = __Infer<typeof BackfillEloReducer>;
export type BackfillTopBidArchiveParams = __Infer<typeof BackfillTopBidArchiveReducer>;
export type BootstrapAdminParams = __Infer<typeof BootstrapAdminReducer>;
export type ClaimCredentialParams = __Infer<typeof ClaimCredentialReducer>;
export type ConnectIdParams = __Infer<typeof ConnectIdReducer>;
export type CreateTeamParams = __Infer<typeof CreateTeamReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type JoinTeamParams = __Infer<typeof JoinTeamReducer>;
export type LeaveTeamParams = __Infer<typeof LeaveTeamReducer>;
export type MintCredentialNonceParams = __Infer<typeof MintCredentialNonceReducer>;
export type PromoteToOwnerParams = __Infer<typeof PromoteToOwnerReducer>;
export type RemoveAdminParams = __Infer<typeof RemoveAdminReducer>;
export type SpawnSimulatedBotParams = __Infer<typeof SpawnSimulatedBotReducer>;
export type StartTournamentParams = __Infer<typeof StartTournamentReducer>;
export type SubmitBidParams = __Infer<typeof SubmitBidReducer>;
export type SubmitWordParams = __Infer<typeof SubmitWordReducer>;

